// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package edu.nr.main.subsystems;
import edu.nr.main.commands.DriveDriveCommand;
import edu.nr.main.robot_map;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class drv extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar cANJaguar1 = robot_map.frontLeftJag;
    CANJaguar cANJaguar2 = robot_map.rearLeftJag;
    CANJaguar cANJaguar3 = robot_map.frontRightJag;
    CANJaguar cANJaguar4 = robot_map.rearRightJag;
    RobotDrive robotDrive41 = robot_map.nrDrive;
    Gyro gyro1 = robot_map.driveGyro;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new DriveDriveCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public double getGyroAngle()
    {
	    return gyro1.getAngle();
    }
    public void driveMecanum(float x, float y, float z)
    {
	    robotDrive41.mecanumDrive_Cartesian(x, y, z, 0);
    }
}
