// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package edu.nr.main.subsystems;
import edu.nr.main.commands.TrackIdleCommand;
import edu.nr.main.robot_map;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class trck extends Subsystem 
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Encoder encoder = robot_map.trackEncoder;
    AnalogChannel force1 = robot_map.trackForce1;
    AnalogChannel force2 = robot_map.trackForce2;
    Solenoid brakeSolenoid = robot_map.trackBrakeSolenoid;
    SpeedController vic1 = robot_map.trackVic1;
    SpeedController vic2 = robot_map.trackVic2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() 
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new TrackIdleCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void drive(double speed) {
	vic1.set(speed);
	vic2.set(speed);
    }    
    
    public void brake() {
        drive(0.0);
	brakeSolenoid.set(true);
    }
    
    public void stop() {
        brake();
    }
            
}