// robotBuilder Version: 0.0.2
//
// This file was generated by robotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from robotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package edu.nr.main.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.nr.main.RobotMain;
/**
 *
 */
public class  DriveTrack extends Command {
    float m_speed;
    public DriveTrack(float speed) 
    {
        m_speed = speed;
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(RobotMain.track);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        RobotMain.track.brake();
        
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        if(m_speed > 0)
        {
                if(timeSinceInitialized() > 1)
                {
                        RobotMain.track.drive(m_speed);
                }
        }
        else
        {
                if(timeSinceInitialized() > 1)
                {
                        RobotMain.track.drive(m_speed);
                }
        }
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
        RobotMain.track.drive(0);
        RobotMain.track.brake();
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        RobotMain.track.drive(0);
        RobotMain.track.brake();
    }
}
