// robotBuilder Version: 0.0.2
//
// This file was generated by robotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from robotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package edu.nr.main.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.nr.main.RobotMain;
/**
 *
 */
public class  DriveUsingJoystick extends Command {
    private final float m_x;
    private final float m_y;
    private final float m_time;
    public DriveUsingJoystick(float x, float y, float time) {
        m_x = x;
        m_y = y;
        m_time = time;
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(RobotMain.drive);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        RobotMain.drive.driveMecanum(m_x, m_y, 0);

    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return (timeSinceInitialized() >= m_time);

    }
    // Called once after isFinished returns true
    protected void end() {
        RobotMain.drive.driveMecanum(0,0,0);

    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        RobotMain.drive.driveMecanum(0,0,0);

    }
}
