// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package edu.nr.main.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.nr.main.Robot;
/**
 *
 */
public class  DriveRotateCommand extends Command {
    float m_deltaAngle;
    float m_initialAngle;
    float m_speed;
    public DriveRotateCommand(float speed, float angle) {
        m_speed = speed;
        m_deltaAngle = angle;
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
                m_initialAngle = (float) Robot.drive.getGyroAngle();

    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        Robot.drive.driveMecanum(0, 0, m_speed);
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return (Robot.drive.getGyroAngle() >= m_initialAngle + m_deltaAngle);
    }
    // Called once after isFinished returns true
    protected void end() {
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
