// robotBuilder Version: 0.0.2
//
// This file was generated by robotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from robotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package edu.nr.main.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.nr.main.robot;
import edu.nr.main.gamepad;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
/**
 *
 */
public class  drv_drv extends Command {
    private float snapx;
    private float snapy;
    private float snapz;
    
    public double lastExecuteTime;

    public drv_drv() {
        
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(robot.drive);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        if(robot.oi.getPadRawAxis(gamepad.kDPadXAxis)  > 0)
        {
                robot.drive.driveMecanum(-0.2f, 0, 0);
        }
        else if(robot.oi.getPadRawAxis(gamepad.kDPadXAxis) < 0)
        {
                robot.drive.driveMecanum(0.2f, 0, 0);
        }
        else if(robot.oi.getPadRawAxis(gamepad.kDPadYAxis)  > 0)
        {
                robot.drive.driveMecanum(0, 0.2f, 0);
        }
        else if(robot.oi.getPadRawAxis(gamepad.kDPadYAxis)  < 0)
        {
                robot.drive.driveMecanum(0, -0.2f, 0);
        }
        else
        {        
            /***********
             * FIXME Some of the axes are reversed!
             ***********/
            //SNAP X
            if(robot.oi.getPadRawAxis(gamepad.kLeftXAxis) < 0.08 && robot.oi.getPadRawAxis(gamepad.kLeftXAxis) > -0.08)
                    snapx = 0;
            else
                    snapx = robot.oi.getPadRawAxis(gamepad.kLeftXAxis);
            //SNAP Y
            if(robot.oi.getPadRawAxis(gamepad.kLeftYAxis) < 0.08 && robot.oi.getPadRawAxis(gamepad.kLeftYAxis) > -0.08)
                    snapy = 0;
            else
                    snapy = -robot.oi.getPadRawAxis(gamepad.kLeftYAxis);
            //SNAP Z
            if(robot.oi.getPadRawAxis(gamepad.kRightXAxis) < 0.08 && robot.oi.getPadRawAxis(gamepad.kRightXAxis) > -0.08)
                    snapz = 0;
            else
                    snapz = -robot.oi.getPadRawAxis(gamepad.kRightXAxis);

            //Cut the rotation speed in half (because it is way too fast as it is)
            snapz /= 2;

            snapx *= 0.65;
            snapy *= 0.65;

            //Cut down all the speeds if the right bumper is being held (for fine alignment)
            if(robot.oi.getPadButton(gamepad.kRightBumper))
            {
                    snapx /= 2;
                    snapy /= 2;
                    snapz /= 2;
            }
            SmartDashboard.putNumber("Snapx", snapx);
            SmartDashboard.putNumber("Snapy", snapy);
            SmartDashboard.putNumber("Snapz", snapz);

            robot.drive.driveMecanum(snapx, snapy, snapz);
        }
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
