// robotBuilder Version: 0.0.2
//
// This file was generated by robotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from robotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package edu.nr.main.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.command.WaitCommand;

/**
 *
 */
public class ShootFourFrisbees extends CommandGroup {
    
    public  ShootFourFrisbees() {
        addSequential(new RunShooter());
        addSequential(new WaitCommand(4));
        
        addSequential(new LoadShooter());
        addSequential(new WaitCommand(3));
        
        addSequential(new LoadShooter());
        addSequential(new WaitCommand(3));
        
        addSequential(new LoadShooter());
        addSequential(new WaitCommand(3));
        
        addSequential(new LoadShooter());
        
        addSequential(new StopShooter());
    }
}
