// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package com.nashobarobotics.subsystems;
import com.nashobarobotics.RobotMap;
import com.nashobarobotics.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class PneumaticsCompressor extends Subsystem 
{
    private boolean automatic = false;
    Relay compressorRelay = RobotMap.compressorRelay;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DigitalInput digitalInput1 = RobotMap.pneumaticsCompressorDigitalInput1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() 
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new CompressorIdleCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void toggleAutomatic()
    {
	automatic = !automatic;
    }
    
    public boolean getAutomatic()
    {
	return automatic;
    }
    
    public void setCompressor(boolean value)
    {
	compressorRelay.set((value)?Relay.Value.kOn:Relay.Value.kOff);
    }
    
    public boolean pressureIsFull()
    {
	return digitalInput1.get();
    }
}